application:
  name: dev环境 @artifactId@
  version: dev环境 @version@
developer:
  name: dev环境
  website: dev环境 网页测试
  qq: dev环境 111111111
  phone-number: dev环境 111111111111
test:
  name: dev环境
  txt: 这是以测试环境的配置运行的

