application:
  name: prod环境 @artifactId@
  version: prod环境 @version@
developer:
  name: prod环境 zhouhao
  website: prod环境 https://zhouhao.com
  qq: prod环境 735652914
  phone-number: prod环境 15910531627
test:
  name: prod环境
  txt: 这是以prod环境的配置运行的
